export const ANALYSE_ADDED="ANALYSE_ADDED";
export const ANALYSE_FAILED="ANALYSE_FAILED";
export const ANALYSE_LOADING="ANALYSE_LOADING";
export const GET_ANALYS="GET_ANALYS";
export const GET_FAILED_ANALYS="GET_FAILED_ANALYS";
export const DELETE_ANSUCCESS="DELETE_ANSUCCESS";
export const DELETE_ANFAIL="DELETE_ANFAIL";

